apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: step4api/service:3
        volumeMounts:
        - name: api-config
          mountPath: /etc/ccts/config.yaml
        ports:
        - containerPort: 5001

