apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: step4app/service:3
        volumeMounts:
        - name: app-config
          mountPath: /etc/ccts/config.yaml
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config
          mountPath: /etc/ccts/config.yaml
      volumes:
      - name: config
        configMap:
          name: app-config
